id: opecha:P009502
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC346
  title: "མཁས་དབང་ཚུལ་ཁྲིམས་བློ་གྲོས་ཀྱིས་སི་ཁྲོན་ཞིང་ཆེན་བོད་ཡིག་སློབ་གྲྭར་གནང་བའི་འཆད་ཁྲིད།\
    \ མཐའ་གཉིས་རབ་སེལ། \n"
  volume: ''
  author: ''
