id: P009502
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC346
  title: "མཁས་དབང་ཚུལ་ཁྲིམས་བློ་གྲོས་ཀྱིས་སི་ཁྲོན་ཞིང་ཆེན་བོད་ཡིག་སློབ་གྲྭར་གནང་བའི་འཆད་ཁྲིད།
    མཐའ་གཉིས་རབ་སེལ། \n"
  author: ''
  volumes:
    49e2d24eaf564ae5a4dde82d3becf06f:
      image_group_id: I2PD17863
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
